# Generated by Django 4.1.4 on 2022-12-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('img_url', models.CharField(max_length=400)),
                ('descripcion', models.CharField(max_length=400)),
                ('tags', models.CharField(choices=[('python', 'Python'), ('css', 'CSS'), ('html', 'HTML'), ('javascript', 'Javascript'), ('etc', 'Etc')], max_length=100)),
                ('url_github', models.CharField(max_length=400)),
            ],
        ),
    ]
