# Generated by Django 4.1.4 on 2022-12-11 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addproject', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='descripcion',
            new_name='description',
        ),
    ]
