# Generated by Django 4.1.4 on 2022-12-11 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addproject', '0002_rename_descripcion_project_description'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table='projects',
        ),
    ]
